import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import { useState } from 'react'
import axios from 'axios'

const inter = Inter({ subsets: ['latin'] })


export default function Home() {
  const [location, setLocation] = useState('');
  const [data, setData] = useState({});
  const [weather,setWeather] = useState();
  const [errorMessage, setErrorMessage] = useState("")

  var apiKey = "c673d0f9b1c4a5656b7593b911acea39";
  var lang = "fr";
  var units = "metric";

  const url = `https://api.openweathermap.org/data/2.5/weather?q=${location}&units=${units}&appid=${apiKey}&lan=${lang}`
  const searchLocation = (event) => {
    if(event.key === "Enter") {
      axios.get(url)
      .then((response)=>{
        console.clear();
        setData(response.data);
        console.log(response.data);
        setWeather(response.data.weather);
        setErrorMessage("");
      }).catch(err=>{
        console.log(err);
        setErrorMessage("Please enter another location");
        setData({});
        setWeather();
      })
      setLocation('');
    }
  }

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        {errorMessage}
        <h2 className={styles.title}>Location {data.name}</h2>
      <div className='parent'>
        <input
          value={location}
          onChange={event => setLocation(event.target.value)}
          placeholder="Enter Location"
          onKeyDown={searchLocation}
          type="text"
        />
      </div>
        {
          weather && weather.map((w, index) =>{
            return(
              <div key={index} className>
                <li>Weather type:</li>
                <div>{w.main}</div>
                <li>Weather description:</li>
                <div>{w.description}</div>
                <li>Temperature:</li>
                <div>{data.main.temp}</div>
                <li>Feels like:</li>
                <div>{data.main.feels_like}</div>
              </div>
            )
          })
        }
      </main>
    </>
  )
}
